---
buildpack: https://github.com/cloudfoundry/go-buildpack.git#v1.7.8
domain: cloud.gov
memory: 256M
services:
  - deck-ups
env:
  GOVERSION: go1.6.2
  GOPACKAGENAME: github.com/18F/cg-deck
  GO15VENDOREXPERIMENT: 1
